-- begin MAILREADER_TASK
create unique index IDX_MAILREADER_TASK_UNIQ_SHORTDESC on MAILREADER_TASK (SHORTDESC) ^
-- end MAILREADER_TASK
-- begin MAILREADER_TRACKER
alter table MAILREADER_TRACKER add constraint FK_MAILREADER_TRACKER_ON_PROJECT foreign key (PROJECT_ID) references MAILREADER_TASK(ID)^
create index IDX_MAILREADER_TRACKER_ON_PROJECT on MAILREADER_TRACKER (PROJECT_ID)^
-- end MAILREADER_TRACKER
